#!/bin/sh

echo "Running pre-commit hook"

# Run prettier
echo "🎨 Running prettier"
npx prettier --check domain/* app/* presentation/*

if [ $? -ne 0 ]; then 
    echo "Prettier failed 🔴, please run 'npx prettier --write domain/* app/* presentation/*' and commit again"
    exit 1
fi

# Run eslint
echo "🔍 Running eslint"
npx eslint domain/* app/* presentation/*
if [ $? -ne 0 ]; then 
    echo "Eslint failed 🔴, please fix linting issues. and commit again"
    exit 1
fi

echo "✅ All checks passed"


